// Code generated by Slice Machine. DO NOT EDIT.

import RichText from './RichText/index.svelte';
import Swag from './Swag/index.svelte';

export const components = {
	rich_text: RichText,
	swag: Swag
};
