// Code generated by Slice Machine. DO NOT EDIT.

import ImageTest from './ImageTest/index.svelte';
import Links from './Links/index.svelte';
import RichText from './RichText/index.svelte';

export const components = {
	image_test: ImageTest,
	links: Links,
	rich_text: RichText
};
